// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateOrderInput struct {
	Price float64 `json:"price"`
	Tax   float64 `json:"tax"`
}

type Mutation struct {
}

type Query struct {
}
