// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewOrder struct {
	Customer string          `json:"customer"`
	Items    []*NewOrderItem `json:"items"`
}

type NewOrderItem struct {
	Product  string  `json:"product"`
	Price    float64 `json:"price"`
	Quantity int     `json:"quantity"`
}

type Query struct {
}
